slogan: "目前还是想学一点东西，学什么东西随缘qwq。反正肯定是计算机跑不了qwq"

theme: bootstrap
inverse: true

menu:
  - title: 所有文章就是所有文章
    url: archives
    intro: "就是所有文章"
    icon: "fa fa-archive"
  - title: 各种分类就是各种分类
    url: categories
    intro: "就是各种分类，没怎么分好类qwq"
    icon: "fa fa-folder"
  - title: 标签就是标签
    url: tags
    intro: "分类的标签"
    icon: "fa fa-tags"
  - title: 关于我就是关于我
    url: about
    intro: "想了解我是不是qwq"
    icon: "fa fa-user"

links:
  - title: 这个网站的网址
    url: https://github.com/hgkdzbf6/
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/wzpan
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: http://www.linkedin.com/in/hahack
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

auto_excerpt:
  enable: true
  length: 150

widgets:
- search
- recent_comments
- category
- tagcloud
- recent_posts
- links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname: #freemindtheme

# Recommended posts
# Dependency: https://github.com/huiwang/hexo-recommended-posts
recommended_posts:
  enabled: false

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR


# share widgets
bdshare: true
jiathis: false

# built-in comment system
comment_js:
  type: "github"
  user: "wzpan"
  repo: "hexo-theme-freemind-blog"
  client_id: "bf7d4ba11877db88543e"
  client_secret: "bff8a6b06b745c0bfcdccbe225623ea8e2a057bb"
  count: 5
